#!/bin/bash
#
# This script will dump the contents of the MySQL database to files.
#

. ./mysql_info

function dump_data ()
{
    echo -n "Dumping contents of $1:$3 ..."
    [ ! -d $2 ] && mkdir $2
    mysqldump$OPTS -e -Q --skip-dump-date --add-drop-table $1 $3 >$2/$3.sql
    echo " done"
}

function dump_struc ()
{
    echo -n "Dumping structure of $1:$3 ..."
    [ ! -d $2 ] && mkdir $2
    mysqldump$OPTS -e -Q --skip-dump-date --add-drop-table --no-data $1 $3 >$2/$3.sql
    echo " done"
}

#
# ScriptDev database
#
dump_data wowc_scriptdev zp_scripts gossip_texts
dump_data wowc_scriptdev zp_scripts script_texts
dump_data wowc_scriptdev zp_scripts script_waypoint
dump_data wowc_scriptdev zp_scripts sd0_db_version
dump_data wowc_scriptdev zp_scripts custom_texts

#
# World database
#
dump_data wowc_world zp_world areatrigger_involvedrelation
dump_data wowc_world zp_world areatrigger_tavern
dump_data wowc_world zp_world areatrigger_teleport
dump_data wowc_world zp_world battleground_events
dump_data wowc_world zp_world battleground_template
dump_data wowc_world zp_world battlemaster_entry
dump_data wowc_world zp_world command
dump_data wowc_world zp_world creature
dump_data wowc_world zp_world creature_addon
dump_data wowc_world zp_world creature_ai_scripts
dump_data wowc_world zp_world creature_ai_summons
dump_data wowc_world zp_world creature_ai_texts
dump_data wowc_world zp_world creature_battleground
dump_data wowc_world zp_world creature_equip_template
dump_data wowc_world zp_world creature_equip_template_raw
dump_data wowc_world zp_world creature_involvedrelation
dump_data wowc_world zp_world creature_loot_template
dump_data wowc_world zp_world creature_model_info
dump_data wowc_world zp_world creature_movement
dump_data wowc_world zp_world creature_movement_scripts
dump_data wowc_world zp_world creature_movement_template
dump_data wowc_world zp_world creature_onkill_reputation
dump_data wowc_world zp_world creature_questrelation
dump_data wowc_world zp_world creature_template
dump_data wowc_world zp_world creature_template_addon
dump_data wowc_world zp_world db_script_string
dump_data wowc_world zp_world db_version
dump_data wowc_world zp_world disenchant_loot_template
dump_data wowc_world zp_world event_scripts
dump_data wowc_world zp_world exploration_basexp
dump_data wowc_world zp_world fishing_loot_template
dump_data wowc_world zp_world gameobject
dump_data wowc_world zp_world gameobject_battleground
dump_data wowc_world zp_world gameobject_involvedrelation
dump_data wowc_world zp_world gameobject_loot_template
dump_data wowc_world zp_world gameobject_questrelation
dump_data wowc_world zp_world gameobject_scripts
dump_data wowc_world zp_world gameobject_template
dump_data wowc_world zp_world game_event
dump_data wowc_world zp_world game_event_creature
dump_data wowc_world zp_world game_event_creature_data
dump_data wowc_world zp_world game_event_gameobject
dump_data wowc_world zp_world game_event_mail
dump_data wowc_world zp_world game_event_quest
dump_data wowc_world zp_world game_graveyard_zone
dump_data wowc_world zp_world game_tele
dump_data wowc_world zp_world game_weather
dump_data wowc_world zp_world gossip_menu
dump_data wowc_world zp_world gossip_menu_option
dump_data wowc_world zp_world gossip_scripts
dump_data wowc_world zp_world instance_template
dump_data wowc_world zp_world item_enchantment_template
dump_data wowc_world zp_world item_loot_template
dump_data wowc_world zp_world item_required_target
dump_data wowc_world zp_world item_template
dump_data wowc_world zp_world mail_loot_template
dump_data wowc_world zp_world mangos_string
dump_data wowc_world zp_world npc_gossip
dump_data wowc_world zp_world npc_text
dump_data wowc_world zp_world npc_trainer
dump_data wowc_world zp_world npc_trainer_template
dump_data wowc_world zp_world npc_vendor
dump_data wowc_world zp_world npc_vendor_template
dump_data wowc_world zp_world page_text
dump_data wowc_world zp_world petcreateinfo_spell
dump_data wowc_world zp_world pet_levelstats
dump_data wowc_world zp_world pet_name_generation
dump_data wowc_world zp_world pickpocketing_loot_template
dump_data wowc_world zp_world playercreateinfo
dump_data wowc_world zp_world playercreateinfo_action
dump_data wowc_world zp_world playercreateinfo_item
dump_data wowc_world zp_world playercreateinfo_spell
dump_data wowc_world zp_world player_classlevelstats
dump_data wowc_world zp_world player_levelstats
dump_data wowc_world zp_world player_xp_for_level
dump_data wowc_world zp_world points_of_interest
dump_data wowc_world zp_world pool_creature
dump_data wowc_world zp_world pool_creature_template
dump_data wowc_world zp_world pool_gameobject
dump_data wowc_world zp_world pool_gameobject_template
dump_data wowc_world zp_world pool_pool
dump_data wowc_world zp_world pool_template
dump_data wowc_world zp_world quest_end_scripts
dump_data wowc_world zp_world quest_start_scripts
dump_data wowc_world zp_world quest_template
dump_data wowc_world zp_world reference_loot_template
dump_data wowc_world zp_world reputation_reward_rate
dump_data wowc_world zp_world reputation_spillover_template
dump_data wowc_world zp_world reserved_name
dump_data wowc_world zp_world scripted_areatrigger
dump_data wowc_world zp_world scripted_event_id
dump_data wowc_world zp_world skill_discovery_template
dump_data wowc_world zp_world skill_extra_item_template
dump_data wowc_world zp_world skill_fishing_base_level
dump_data wowc_world zp_world skinning_loot_template
dump_data wowc_world zp_world spell_affect
dump_data wowc_world zp_world spell_area
dump_data wowc_world zp_world spell_bonus_data
dump_data wowc_world zp_world spell_chain
dump_data wowc_world zp_world spell_elixir
dump_data wowc_world zp_world spell_facing
dump_data wowc_world zp_world spell_learn_spell
dump_data wowc_world zp_world spell_pet_auras
dump_data wowc_world zp_world spell_proc_event
dump_data wowc_world zp_world spell_proc_item_enchant
dump_data wowc_world zp_world spell_scripts
dump_data wowc_world zp_world spell_script_target
dump_data wowc_world zp_world spell_target_position
dump_data wowc_world zp_world spell_threat
dump_data wowc_world zp_world transports
dump_data wowc_world zp_world world_template

#
# Dump Locales database tables
#
dump_data wowc_world zp_world locales_creature
dump_data wowc_world zp_world locales_gameobject
dump_data wowc_world zp_world locales_gossip_menu_option
dump_data wowc_world zp_world locales_item
dump_data wowc_world zp_world locales_npc_text
dump_data wowc_world zp_world locales_page_text
dump_data wowc_world zp_world locales_points_of_interest
dump_data wowc_world zp_world locales_quest

# Erstmal nur world und scripts dumpen
exit

#
# Empty character database tables
#
dump_data wowc_characters zp_characters auction
dump_data wowc_characters zp_characters bugreport
dump_data wowc_characters zp_characters characters
dump_data wowc_characters zp_characters character_action
dump_data wowc_characters zp_characters character_aura
dump_data wowc_characters zp_characters character_battleground_data
dump_data wowc_characters zp_characters character_gifts
dump_data wowc_characters zp_characters character_homebind
dump_data wowc_characters zp_characters character_honor_cp
dump_data wowc_characters zp_characters character_instance
dump_data wowc_characters zp_characters character_inventory
dump_data wowc_characters zp_characters character_pet
dump_data wowc_characters zp_characters character_queststatus
dump_data wowc_characters zp_characters character_reputation
dump_data wowc_characters zp_characters character_skills
dump_data wowc_characters zp_characters character_social
dump_data wowc_characters zp_characters character_spell
dump_data wowc_characters zp_characters character_spell_cooldown
dump_data wowc_characters zp_characters character_stats
dump_data wowc_characters zp_characters character_ticket
dump_data wowc_characters zp_characters character_tutorial
dump_data wowc_characters zp_characters corpse
dump_data wowc_characters zp_characters creature_respawn
dump_data wowc_characters zp_characters gameobject_respawn
dump_data wowc_characters zp_characters game_event_status
dump_data wowc_characters zp_characters groups
dump_data wowc_characters zp_characters group_instance
dump_data wowc_characters zp_characters group_member
dump_data wowc_characters zp_characters guild
dump_data wowc_characters zp_characters guild_eventlog
dump_data wowc_characters zp_characters guild_member
dump_data wowc_characters zp_characters guild_rank
dump_data wowc_characters zp_characters instance
dump_data wowc_characters zp_characters instance_reset
dump_data wowc_characters zp_characters item_instance
dump_data wowc_characters zp_characters item_loot
dump_data wowc_characters zp_characters item_text
dump_data wowc_characters zp_characters mail
dump_data wowc_characters zp_characters mail_items
dump_data wowc_characters zp_characters petition
dump_data wowc_characters zp_characters petition_sign
dump_data wowc_characters zp_characters pet_aura
dump_data wowc_characters zp_characters pet_spell
dump_data wowc_characters zp_characters pet_spell_cooldown
dump_data wowc_characters zp_characters saved_variables
dump_data wowc_characters zp_characters world

#
# Empty realm database tables
#
dump_data wowc_realmd zp_realm account_banned
dump_data wowc_realmd zp_realm ip_banned
dump_data wowc_realmd zp_realm realmcharacters
dump_data wowc_realmd zp_realm uptime

#
# Character database
#
#dump_data wowc_characters zp_characters character_db_version

#
# Realm database
#
dump_data wowc_realmd zp_realm account
dump_data wowc_realmd zp_realm realmd_db_version
dump_data wowc_realmd zp_realm realmlist
